Revert of Rename enums/functions that collide in chromium style in WTF::HashMap (patchset #1 id:1 of https://codereview.chromium.org/1746503002/ )
Reason for revert:
https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20non-Oilpan%20Builder/builds/1169/steps/compile/logs/stdio

FAILED: /b/build/goma/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/WebKit/Source/core/dom/CustomElementUpgradeCandidateMap.o.d -DV8_DEPRECATION_WARNINGS -DCLD_VERSION=2 -DENABLE_MDNS=1 -DENABLE_NOTIFICATIONS -DENABLE_PEPPER_CDMS -DENABLE_PLUGINS=1 -DENABLE_PDF=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DUSE_UDEV -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CLIPBOARD_AURAX11=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_GLIB=1 -DUSE_OPENSSL=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DENABLE_WEBRTC=1 -DENABLE_EXTENSIONS=1 -DENABLE_CONFIGURATION_POLICY -DENABLE_TASK_MANAGER=1 -DENABLE_THEMES=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_APP_LIST=1 -DENABLE_SETTINGS_APP=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_TOPCHROME_MD=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=261368-1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DBLINK_CORE_IMPLEMENTATION=1 -DGL_GLEXT_PROTOTYPES -DBLINK_IMPLEMENTATION=1 -DINSIDE_BLINK -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_SUPPORT_GPU=1 -DENABLE_LAYOUT_UNIT_IN_INLINE_BOXES=0 -DWTF_USE_CONCATENATED_IMPULSE_RESPONSES=1 -DENABLE_INPUT_MULTIPLE_FIELDS_UI=1 -DWTF_USE_ICCJPEG=1 -DWTF_USE_QCMSLIB=1 -DWTF_USE_WEBAUDIO_FFMPEG=1 -DWTF_USE_DEFAULT_RENDER_THEME=1 -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DU_STATIC_IMPLEMENTATION -DCHROME_PNG_WRITE_SUPPORT -DPNG_USER_CONFIG -DLIBXSLT_STATIC -I../.. -Igen -I../../third_party/khronos -I../../gpu -I../../build/linux/debian_wheezy_amd64-sysroot/usr/include/glib-2.0 -I../../build/linux/debian_wheezy_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include -I../../third_party/libwebp -I../../third_party/WebKit/Source -Igen/blink -I../../third_party/WebKit/Source -I../../third_party/WebKit -Igen/blink -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/angle/include -I../../third_party/iccjpeg -I../../third_party/libpng -I../../third_party/zlib -I../../third_party/libxml/src/include -I../../third_party/libxml/linux/include -I../../third_party/libxslt -I../../third_party/npapi -I../../third_party/npapi/bindings -I../../third_party/ots/include -I../../third_party/qcms/src -I../../third_party/snappy/src -I../../third_party/snappy/linux -I../../v8/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -fcolor-diagnostics -fdebug-prefix-map=/b/build/slave/WebKit_Linux_non-Oilpan_Builder/build/src=. -pthread -m64 -march=x86-64 -Wall -Wextra -Werror -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-deprecated-register -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-shift-negative-value -O2 -fno-ident -fdata-sections -ffunction-sections -g0 --sysroot=../../build/linux/debian_wheezy_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-templates -Xclang -plugin-arg-find-bad-constructs -Xclang follow-macro-expansion -Wheader-hygiene -Wstring-conversion -Wexit-time-destructors -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libBlinkGCPlugin.so -Xclang -add-plugin -Xclang blink-gc-plugin -DLIBXML_STATIC= -fno-threadsafe-statics -fvisibility-inlines-hidden -std=gnu++11 -fno-rtti -fno-exceptions -c ../../third_party/WebKit/Source/core/dom/custom/CustomElementUpgradeCandidateMap.cpp -o obj/third_party/WebKit/Source/core/dom/CustomElementUpgradeCandidateMap.o
../../third_party/WebKit/Source/core/dom/custom/CustomElementUpgradeCandidateMap.cpp:47:79: error: no member named 'keys' in 'WTF::HashTableIteratorAdapter<WTF::HashTable<blink::Element *, WTF::KeyValuePair<blink::Element *, blink::CustomElementDescriptor>, WTF::KeyValuePairKeyExtractor, WTF::PtrHash<WTF::RawPtr<blink::Element> >, WTF::HashMapValueTraits<WTF::HashTraits<WTF::RawPtr<blink::Element> >, WTF::HashTraits<blink::CustomElementDescriptor> >, WTF::HashTraits<WTF::RawPtr<blink::Element> >, WTF::PartitionAllocator>, WTF::KeyValuePair<blink::Element *, blink::CustomElementDescriptor> >'
    UpgradeCandidateMap::const_iterator::Keys end = m_upgradeCandidates.end().keys();
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~ ^
../../third_party/WebKit/Source/core/dom/custom/CustomElementUpgradeCandidateMap.cpp:48:85: error: no member named 'keys' in 'WTF::HashTableIteratorAdapter<WTF::HashTable<blink::Element *, WTF::KeyValuePair<blink::Element *, blink::CustomElementDescriptor>, WTF::KeyValuePairKeyExtractor, WTF::PtrHash<WTF::RawPtr<blink::Element> >, WTF::HashMapValueTraits<WTF::HashTraits<WTF::RawPtr<blink::Element> >, WTF::HashTraits<blink::CustomElementDescriptor> >, WTF::HashTraits<WTF::RawPtr<blink::Element> >, WTF::PartitionAllocator>, WTF::KeyValuePair<blink::Element *, blink::CustomElementDescriptor> >'
    for (UpgradeCandidateMap::const_iterator::Keys it = m_upgradeCandidates.begin().keys(); it != end; ++it)
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
2 errors generated.

CQ doesn't build this?

Original issue's description:
> Rename enums/functions that collide in chromium style in WTF::HashMap
>
> R=esprehn@chromium.org, thakis@chromium.org
> BUG=582312
>
> Committed: https://crrev.com/477aebd4f13056c90a257b78c1f572d910c85f19
> Cr-Commit-Position: refs/heads/master@{#378312}

TBR=tkent@chromium.org,esprehn@chromium.org,jyasskin@chromium.org,thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=582312

Review URL: https://codereview.chromium.org/1745343002

Cr-Original-Commit-Position: refs/heads/master@{#378315}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: beab086f2531fb71d06b49ee23da38fa80fb0584