Roll src/third_party/libvpx_new/source/libvpx/ f51dd8c2a..f288c943c (39 commits).
https://chromium.googlesource.com/webm/libvpx.git/+log/f51dd8c2ac7d..f288c943c4d6

$ git log f51dd8c2a..f288c943c --date=short --no-merges --format='%ad %ae %s'
2016-02-08 marpan vp9-dynamic resize: Fix bug on releasing scaled reference.
2016-02-08 marpan vp9-aq-mode=3: Reset cyclic refresh under config/external size change.
2016-02-08 Yaowu Xu Set use_highbitdepth flag to either 1 or 0
2016-02-08 debargha Explicitly set tx_type for sub8x8 blocks
2016-02-08 slavarnway BUG FIX: undefined reference to `vp9_scale_and_extend_frame_c'
2016-02-08 marpan vp9-denoiser: Allow for checking skin for bsize <=32x32.
2016-02-08 jingning Account for sub8x8 block skip mode cost in RD decision
2016-02-08 jingning Clean up in vp9_rd_pick_inter_mode_sb
2016-02-05 marpan vp9-dynamic resize: On a resize trigger frame refresh alt_ref.
2016-02-05 aconverse Fix an uninitialized warning.
2016-02-05 jzern vp9_aq_cyclicrefresh: fix unused-function warning
2016-02-04 marpan vp9 aq-mode=3: Keep it on even at low bitrates.
2016-02-04 slavarnway Vidyo patch: Optimization for 1-to-2 downsampling and upsampling.
2016-02-04 zoeliu Define a macro to replace hardcoded values
2016-02-01 jzern configure: enable -Wunused-function by default
2016-02-03 jzern fdct8x8_test:: quiet unused-function warning
2016-02-03 marpan vp9-skinmap. Some adjustments for model=1.
2016-02-03 jingning Use precise rate cost estimate for skip block mode
2016-02-02 jzern dct16x16_test: quiet unused-function warning
2016-02-02 jzern intrapred: protect functions w/CONFIG check x2
(...)

R=johannkoenig@google.com
BUG=

Review URL: https://codereview.chromium.org/1690023003

Cr-Original-Commit-Position: refs/heads/master@{#375038}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 58c3617b0fe7a79657ecb4a52761612d857a0182