Revert of ImageDocumentParser should stop sending data to ImageResource once decoding fails. (patchset #3 id:40001 of https://codereview.chromium.org/2262833002/ )
Reason for revert:
Reverting due to webkit_unit_test failures on builder "Mac ASan 64 Tests (1)":

https://build.chromium.org/p/chromium.memory/builders/Mac%20ASan%2064%20Tests%20(1)

Output from
https://build.chromium.org/p/chromium.memory/builders/Mac%20ASan%2064%20Tests%20%281%29/builds/20849/steps/webkit_unit_tests%20on%20Mac-10.9/logs/stdio

[ RUN      ] WebFrameTest.ImageDocumentDecodeError
[       OK ] WebFrameTest.ImageDocumentDecodeError (87 ms)
[562/3806] WebFrameTest.ImageDocumentDecodeError (87 ms)
[ RUN      ] CompositedSelectionBoundsTest.None
ASAN:DEADLYSIGNAL
=================================================================
==91966==ERROR: AddressSanitizer: SEGV on unknown address 0x000045e0360e (pc 0x000045e0360e bp 0x7fff5f436950 sp 0x7fff5f436398 T0)
==91966==The signal is caused by a READ memory access.
    #0 0x45e0360d in
Traceback (most recent call last):
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/asan_symbolize.py", line 271, in <module>
    main()
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/asan_symbolize.py", line 268, in main
    loop.process_logfile()
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 416, in process_logfile
    processed = self.process_line(line)
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 439, in process_line_posix
    symbolized_line = self.symbolize_address(addr, binary, offset)
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 393, in symbolize_address
    result = symbolizers[binary].symbolize(addr, binary, offset)
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 244, in symbolize
    result = symbolizer.symbolize(addr, binary, offset)
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 216, in symbolize
    atos_line = self.atos.convert('0x%x' % int(offset, 16))
  File "/b/swarm_slave/w/irrExke3/tools/valgrind/asan/third_party/asan_symbolize.py", line 192, in convert
    self.w.write(line + "\n")
IOError: [Errno 5] Input/output error

Original issue's description:
> ImageDocumentParser should stop sending data to ImageResource once decoding fails.
>
> BUG=635448
> TEST=WebFrameTest.ImageDocumentDecodeError
>
> Committed: https://crrev.com/2fb53d05488ff879e38553839f174f15af2af39b
> Cr-Commit-Position: refs/heads/master@{#413539}

TBR=pdr@chromium.org,japhet@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635448

Review-Url: https://codereview.chromium.org/2264333002
Cr-Original-Commit-Position: refs/heads/master@{#413587}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b2a8e95798c79844c95f9af6fec979500ba09eff