Revert "Barcode detection: split mojo interface into BarcodeDetection and Provider"
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.chromiumos%2FLinux_ChromiumOS_Builder__dbg_%2F90023%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

Failing bots due to 
FAILED: obj/services/shape_detection/lib/barcode_detection_provider_impl.o 
/b/c/goma_client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/services/shape_detection/lib/barcode_detection_provider_impl.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_ASH=1 -DUSE_AURA=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"308728-3\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DOS_CHROMEOS -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_GLIBCXX_DEBUG=1 -DGL_GLEXT_PROTOTYPES -DUSE_GLX -DUSE_EGL -DU_USING_ICU_NAMESPACE=0 -DU_ENABLE_DYLOAD=0 -DICU_UTIL_DATA_IMPL=ICU_UTIL_DATA_FILE -DUCHAR_TYPE=uint16_t -DGOOGLE_PROTOBUF_NO_RTTI -DGOOGLE_PROTOBUF_NO_STATIC_INITIALIZER -DHAVE_PTHREAD -DPROTOBUF_USE_DLLS -DSK_IGNORE_LINEONLY_AA_CONVEX_PATH_OPTS -DSK_HAS_PNG_LIBRARY -DSK_HAS_WEBP_LIBRARY -DSK_HAS_JPEG_LIBRARY -DSKIA_DLL -DGR_GL_IGNORE_ES3_MSAA=0 -DSK_SUPPORT_GPU=1 -DMESA_EGL_NO_X11_HEADERS -I../.. -Igen -I../../third_party/libwebp/src -I../../third_party/khronos -I../../gpu -I../../third_party/ced/src -I../../third_party/icu/source/common -I../../third_party/icu/source/i18n -I../../third_party/protobuf/src -I../../skia/config -I../../skia/ext -I../../third_party/skia/include/c -I../../third_party/skia/include/config -I../../third_party/skia/include/core -I../../third_party/skia/include/effects -I../../third_party/skia/include/encode -I../../third_party/skia/include/images -I../../third_party/skia/include/lazy -I../../third_party/skia/include/pathops -I../../third_party/skia/include/pdf -I../../third_party/skia/include/pipe -I../../third_party/skia/include/ports -I../../third_party/skia/include/utils -I../../third_party/skia/third_party/vulkan -I../../third_party/skia/include/gpu -I../../third_party/skia/src/gpu -I../../third_party/skia/src/sksl -I../../third_party/mesa/src/include -I../../third_party/libwebm/source -fno-strict-aliasing -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -fdebug-prefix-map=/b/c/b/linux_chromeos/src=. -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf --sysroot=../../build/linux/debian_jessie_amd64-sysroot -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wno-undefined-bool-conversion -Wno-tautological-undefined-compare -std=gnu++11 -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../services/shape_detection/barcode_detection_provider_impl.cc -o obj/services/shape_detection/lib/barcode_detection_provider_impl.o
../../services/shape_detection/barcode_detection_provider_impl.cc:18:27: error: chosen constructor is explicit in copy-initialization
  std::move(callback).Run({});
                          ^~
../../build/linux/debian_jessie_amd64-sysroot/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/debug/vector:79:7: note: explicit constructor declared here
      vector(const _Allocator& __a = _Allocator())
      ^
../../base/callback.h:83:17: note: passing argument to parameter 'args' here
  R Run(Args... args) && {
                ^
1 error generated.


Revert "Barcode detection: split mojo interface into BarcodeDetection and Provider"

This reverts commit bb470a5855c77471effbaae6cfb41c1253b60191.

Reason for revert: <INSERT REASONING HERE>

Original change's description:
> Barcode detection: split mojo interface into BarcodeDetection and Provider
> 
> This CL splits the current shape_detection::mojom::BarcodeDetection
> into a BarcodeDetection proper and a BarcodeDetectionProvider (following
> a pattern similar to shape_detection::mojom::FaceDetection and
> FaceDetectionProvider). This division is reflected in the Mac and Android
> implementations.
> 
> The splitting is needed to add enumeration of the supported formats 
> (pre construction) and constructor options.  Wiring those in idl will
> happen in a subsequent CL, to limit the review cycles.
> 
> This CL also adds the necessary data types enum BarcodeFormat and 
> struct BarcodeDetectorOptions, which mimic the ones introduced
> in the WICG spec update that originated the issue tracker.
> 
> Layouttests (and the mock js service) and unittests updated.
> 
> 
> Bug: 747199
> Change-Id: Ib2ffa361465c50999f9c74537d9d7988fa30cd05
> Cq-Include-Trybots: master.tryserver.chromium.linux:linux_site_isolation;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel
> Reviewed-on: https://chromium-review.googlesource.com/582266
> Reviewed-by: Reilly Grant <reillyg@chromium.org>
> Reviewed-by: Avi Drissman <avi@chromium.org>
> Reviewed-by: Tom Sepez <tsepez@chromium.org>
> Commit-Queue: Miguel Casas <mcasas@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#490210}

TBR=avi@chromium.org,reillyg@chromium.org,mcasas@chromium.org,tsepez@chromium.org

Change-Id: Iaf6714f6f90845dfc06b0174c2e98eff62210b2e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 747199
Cq-Include-Trybots: master.tryserver.chromium.linux:linux_site_isolation;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel
Reviewed-on: https://chromium-review.googlesource.com/590593
Commit-Queue: Miguel Casas <mcasas@chromium.org>
Reviewed-by: Miguel Casas <mcasas@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#490225}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 0adc7cd14864359055909e55464ee563d27af6cb