Re-enable TextFloatsAroundFloatsBefore and check left offsets only
http://crrev.com/2739683006 broke one of downstream bots
"WebKit Android (Nexus4)"
Here is the bot's output
  Value of: inline_text_box2->frameRect().location()
   Actual: "30,23"
  Expected: LayoutPoint(30, 22)
   Which is: "30,22"
  Value of: inline_text_box3->frameRect().location()
   Actual: "0,46"
  Expected: LayoutPoint(0, 44)
   Which is: "0,44"

I think it happened because of the difference in sizes between
different fallback fonts on different platforms. I don't have
permissions to run a downstream bot

$ git cl try -m master.chromium.webkit -b "WebKit Android (Nexus4)"
ERROR: Access denied: User user:glebl@chromium.org cannot
add builds to bucket master.chromium.webkit

But it's clear that the test failed while checking the height.

This patch re-enable TextFloatsAroundFloatsBefore and make it to check
what matters, i.e. left offsets.

BUG=700868

Review-Url: https://codereview.chromium.org/2744213004
Cr-Original-Commit-Position: refs/heads/master@{#456467}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fdda6d5acfde5d7083995597ddddeb08588728cd