Revert of Setting link.sizes.value should be reflected in the sizes attribute. (patchset #8 id:140001 of https://codereview.chromium.org/1435223002/ )
Reason for revert:
This broke the compile on Webkit Linux Oilpan builders:

https://build.chromium.org/p/chromium.webkit/builders/WebKit%20Linux%20Oilpan/builds/31014

HTMLLinkElement.h:130:19: error: abstract class is marked 'final'.

Original issue's description:
> Setting link.sizes.value should be reflected in the sizes attribute.
>
> BUG=545518
>
> Committed: https://crrev.com/f3fec1337a6ae3433a378e2742d3d6e968970257
> Cr-Commit-Position: refs/heads/master@{#360008}

TBR=tkent@chromium.org,dcheng@chromium.org,dominicc@chromium.org
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=545518

Review URL: https://codereview.chromium.org/1455433002

Cr-Original-Commit-Position: refs/heads/master@{#360015}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 9afc6ce89e762f5f755a67441267c1fab2ca65c2