Revert of Remove redundant 'derived constraint space' setters from NGConstraintSpace (patchset #2 id:40001 of https://codereview.chromium.org/2515923002/ )
Reason for revert:
Causing wide-spread build failures, with errors like:

../../third_party/WebKit/Source/core/layout/ng/ng_absolute_utils.cc:74:13: error: no member named 'Size' in 'blink::NGConstraintSpace'
      space.Size().ConvertToPhysical(space.WritingMode());
      ~~~~~ ^

Original issue's description:
> Remove redundant 'derived constraint space' setters from NGConstraintSpace
>
> Remove
>   SetOverflowTriggersScrollbar
>   SetFixedSize
>   SetFragmentationType
>   SetIsNewFormattingContext
>   SetSize
>   Size
> from NGConstraintSpace. Use NGConstraintSpaceBuilder instead.
>
> BUG=635619
>
> Committed: https://crrev.com/2bd351a87b733b8b17f6507adb9b6d0829ca978f
> Cr-Commit-Position: refs/heads/master@{#433404}

TBR=ikilpatrick@chromium.org,cbiesinger@chromium.org,glebl@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=635619

Review-Url: https://codereview.chromium.org/2514693004
Cr-Original-Commit-Position: refs/heads/master@{#433405}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fe55fbc67370abded2c79b78b2dad835345b0158