Revert of roll gyp ed163ce233:61259d585c (patchset #2 id:20001 of https://codereview.chromium.org/1766033002/ )
Reason for revert:
win trunk bot started failing after this patch:

[45/14742] CXX obj\third_party\angle\src\libGLESv2\libGLESv2.entry_points_gles_2_0.obj
FAILED: ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs2013_files\4087e065abebdca6dbd0caca2910c6718d2ec67f\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\third_party\webkit\source\build\win\blink_heap_asm_stubs.precompile.obj.rsp /c ..\..\third_party\WebKit\Source\build\win\Precompile.cpp /Foobj\third_party\webkit\source\build\win\blink_heap_asm_stubs.precompile.obj /Fdobj\third_party\WebKit\Source\platform\blink_heap_asm_stubs.cc.pdb
c:\b\build\slave\win_trunk\build\src\third_party\webkit\source\build\win\precompile.cpp : fatal error C1083: Cannot open include file: 'third_party/WebKit/Source/build/win/Precompile.h': No such file or directory
FAILED: ninja -t msvc -e environment.x86 -- "C:\b\depot_tools\win_toolchain\vs2013_files\4087e065abebdca6dbd0caca2910c6718d2ec67f\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\build\harfbuzz-ng.precompile.obj.rsp /c ..\..\build\precompile.cc /Foobj\build\harfbuzz-ng.precompile.obj /Fdobj\third_party\harfbuzz-ng\harfbuzz-ng.cc.pdb
c:\b\build\slave\win_trunk\build\src\build\precompile.cc : fatal error C1083: Cannot open include file: 'build/precompile.h': No such file or directory
ninja: build stopped: subcommand failed.

Builder: https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20trunk

Job: https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20trunk/builds/26144

Logs:https://uberchromegw.corp.google.com/i/official.desktop.continuous/builders/win%20trunk/builds/26144/steps/compile/logs/stdio

Original issue's description:
> roll gyp ed163ce233:61259d585c
>
> 61259d5 ninja/win: Use qualified paths for precompiled headers.
> 1950f67 Xcode-ninja: Add excluded files to the project sources_for_indexing.xcodeproj
> d84fed2 Fix tests with Xcode 7.
> 0cd47bf Make login.keychain and 'Provisioning Profiles' symlinks.
>
> BUG=none
> TBR=scottmg
>
> Committed: https://crrev.com/f90f632aa4e1fc9750ea41a9f6ebdee1240aa678
> Cr-Commit-Position: refs/heads/master@{#379373}

TBR=scottmg@chromium.org,thakis@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=none

Review URL: https://codereview.chromium.org/1759323004

Cr-Original-Commit-Position: refs/heads/master@{#379392}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 765e7b178b46af51727af1972fa08e1fd902f08a