Revert of Add Android implementation of navigator.getInstalledRelatedApps. (patchset #21 id:570001 of https://codereview.chromium.org/2706403014/ )
Reason for revert:
Introduced compile failure.

https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium%2FAndroid%2F70050%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout

../../content/public/android/junit/src/org/chromium/content/browser/installedapp/InstalledAppProviderTest.java:255: error: local variable expectedInstalledRelatedApps is accessed from within inner class; needs to be declared final
                                expectedInstalledRelatedApps.length, installedRelatedApps.length);
                                ^
../../content/public/android/junit/src/org/chromium/content/browser/installedapp/InstalledAppProviderTest.java:259: error: local variable expectedInstalledRelatedApps is accessed from within inner class; needs to be declared final
                                    expectedInstalledRelatedApps[i], installedRelatedApps[i]);

Original issue's description:
> Add Android implementation of navigator.getInstalledRelatedApps.
>
> Based on a CL by dhnishi:
> https://codereview.chromium.org/1756793004/
>
> BUG=587623
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_site_isolation
>
> Review-Url: https://codereview.chromium.org/2706403014
> Cr-Commit-Position: refs/heads/master@{#458632}
> Committed: https://chromium.googlesource.com/chromium/src/+/8773b38c48cf8b27ed4dd1c8ca249944929d3d16

TBR=thakis@chromium.org,nasko@chromium.org,boliu@chromium.org,dcheng@chromium.org,mgiuca@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=587623

Review-Url: https://codereview.chromium.org/2762343003
Cr-Original-Commit-Position: refs/heads/master@{#458642}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 62c02186d3769b4e84cdbcba232fb8ceee6b567f