Reland of In LayoutTests PRESUBMIT, Don't check for all-pass baseline files in platform and virtual. (patchset #1 id:1 of https://codereview.chromium.org/2008753002/ )
Reason for revert:
Creating reland patch (fixing error)

Original issue's description:
> Revert of In LayoutTests PRESUBMIT, Don't check for all-pass baseline files in platform and virtual. (patchset #4 id:60001 of https://codereview.chromium.org/2002513002/ )
>
> Reason for revert:
> This broke presubmit on layout tests with:
> NameError: global name 'expected_files' is not defined
>
> Original issue's description:
> > Don't check for all-pass baseline files in platform and virtual.
> >
> > BUG=613387
> >
> > Committed: https://crrev.com/84044bffc3a99a4eb785ad1b207677a460d6a8e8
> > Cr-Commit-Position: refs/heads/master@{#395370}
>
> TBR=dpranke@chromium.org,tkent@chromium.org,qyearsley@chromium.org
> # Skipping CQ checks because original CL landed less than 1 days ago.
> NOPRESUBMIT=true
> NOTREECHECKS=true
> NOTRY=true
> BUG=613387
>
> Committed: https://crrev.com/b8039077e177e3a636caf28492e9f30c13d97060
> Cr-Commit-Position: refs/heads/master@{#395438}

TBR=dpranke@chromium.org,tkent@chromium.org,caseq@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=613387

Review-Url: https://codereview.chromium.org/2006963002
Cr-Original-Commit-Position: refs/heads/master@{#395473}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 98b84f707fd8961d40e9015cae79370975f1ac69