c++11 ud suffix cleanup for third_party/speech-dispatcher
This merges http://git.freebsoft.org/?p=speechd.git;a=commitdiff;h=c73bfee2b6ef683874b3fe7463239073f703c8b7
to fix

../../third_party/speech-dispatcher/libspeechd.h:42:68: error: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wreserved-user-defined-literal]

This macro moved to a .c file in version 0.8 of this library.

BUG=263960
R=dmazzoni@chromium.org

Review URL: https://codereview.chromium.org/20986006

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 71316604afb68ed5926ff25dc952c4d14000d2c1