Revert of Embedding-CSP: Refactoring directive strings into enum (patchset #6 id:140001 of https://codereview.chromium.org/2516383002/ )
Reason for revert:
Causing WebKit Win x64 Builder to fail on webkit_unit_tests on Windows-7-SP1 ContentSecurityPolicyTest.DirectiveType:
ContentSecurityPolicyTest.DirectiveType (run #1):
[ RUN      ] ContentSecurityPolicyTest.DirectiveType
c:\c\win_layout\src	hird_party\webkit\source\core
rame\csp\contentsecuritypolicytest.cpp(950): error: Death test: ContentSecurityPolicy::getDirectiveName( ContentSecurityPolicy::DirectiveType::Undefined)
    Result: failed to die.
 Error msg:
[  DEATH   ] [3244:5672:1125/030930:3521831:WARNING:test_suite.cc(236)] Test launcher output path C:\Users\CHROME~2\AppData\Local\Temp!6_27934	est_results.xml exists. Not adding test launcher result printer.
[  DEATH   ]
[  FAILED  ] ContentSecurityPolicyTest.DirectiveType (67 ms)

https://uberchromegw.corp.google.com/i/chromium.webkit/builders/WebKit%20Win%20x64%20Builder/builds/101390

Original issue's description:
> Embedding-CSP: Refactoring directive strings into enum.
>
> This is an effort as part of the experimental feature. Causing
> patch: https://codereview.chromium.org/2474903002
>
> BUG=647588
>
> Committed: https://crrev.com/a5e9944b7169dd3a3c9f2cb352aff3551b32cd12
> Cr-Commit-Position: refs/heads/master@{#434474}

TBR=mkwst@chromium.org,jochen@chromium.org,amalika@google.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=647588

Review-Url: https://codereview.chromium.org/2528133002
Cr-Original-Commit-Position: refs/heads/master@{#434483}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: d15fefad6620176d0d0e60588abd29a19acc9d02