Revert 73121 - Remove obsolete files from 'sources'.  This causes needless work on incremental builds in VS2010.
This is breaking clobber builds with this error :
e:\b\build\slave\google-chrome-rel-win\build\src\chrome_frame\iids.cc(6) : fatal error C1083: Cannot open include file: 'chrome_tab.h': No such file or directory


BUG=71130
TEST=Check that Chrome builds.

Review URL: http://codereview.chromium.org/6307018

TBR=jeanluc@chromium.org
Review URL: http://codereview.chromium.org/6347032

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 62ed19af190eade0137c8af80e30f71088a6ba0e