Initialize scm in test_importer, and add unit test.
The latest attempt at auto-import failed because the Git object
of the Host in TestImporter wasn't initialized. See:

https://build.chromium.org/p/chromium.infra.cron/builders/w3c-test-autoroller/builds/7901

Stack trace excerpt:
File ".../webkitpy/w3c/test_importer.py", line 371, in get_directory_owners
  changed_files = self.host.scm().changed_files()
AttributeError: 'NoneType' object has no attribute 'changed_files'
step returned non-zero exit code: 1

Review-Url: https://codereview.chromium.org/2663563002
Cr-Original-Commit-Position: refs/heads/master@{#446870}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 2c0f951aca29cc5b63770a1bfab737f4d75cb758