Revert "Revert "Put BlinkLeakDetector back to core/""
This reverts commit d7e4b96e299571ec466ebd0173edf33c91465fa9.

Reason for revert: Debugging to see if rebase failure was the reason for breaking the build

Original change's description:
> Revert "Put BlinkLeakDetector back to core/"
> 
> This reverts commit 42160bf06117c5c82a27427584c156107d7e8839.
> 
> Reason for revert: Breaks Android Builder
> https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.webkit%2FAndroid_Builder%2F118473%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout
> ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: error: obj/third_party/WebKit/Source/core/leak_detector/libleak_detector.a(BlinkLeakDetector.o): multiple definition of 'blink::BlinkLeakDetector::TimerFiredGC(blink::TimerBase*)'
> ../../third_party/android_tools/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.gold: obj/third_party/WebKit/Source/core/unit_tests/BlinkLeakDetector.o: previous definition here
> 
> Original change's description:
> > Put BlinkLeakDetector back to core/
> > 
> > Although BlinkLeakDetector should and will in the future live in controller/, currently it is better for the code to be in core/ to make it easy to add a devtools protocol method.
> > This CL puts the code back to core/leak_detector.
> > 
> > 
> > Bug: 
> > Change-Id: I863bcbdf9bded868a3aed601cfda8666f1ba67cd
> > Reviewed-on: https://chromium-review.googlesource.com/622816
> > Commit-Queue: Yuzu Saijo <yuzus@chromium.org>
> > Reviewed-by: Kentaro Hara <haraken@chromium.org>
> > Reviewed-by: Keishi Hattori <keishi@chromium.org>
> > Cr-Commit-Position: refs/heads/master@{#495907}
> 
> TBR=haraken@chromium.org,keishi@chromium.org,yuzus@chromium.org
> 
> Change-Id: Ia29383cbd025fc11559cc760c6ba37efb120004c
> No-Presubmit: true
> No-Tree-Checks: true
> No-Try: true
> Reviewed-on: https://chromium-review.googlesource.com/623567
> Reviewed-by: Henrik Kjellander <kjellander@chromium.org>
> Commit-Queue: Henrik Kjellander <kjellander@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#495913}

TBR=kjellander@chromium.org,haraken@chromium.org,keishi@chromium.org,yuzus@chromium.org

Change-Id: I35ac3afa44f36eab884c5fee1d824bb505f126fe
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/625296
Reviewed-by: Kentaro Hara <haraken@chromium.org>
Commit-Queue: Yuzu Saijo <yuzus@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#496169}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 6547e4dc83851dd44acf74e88a8226235b32c2b6