Revert of Blink image-decoders: (lazy) deferred image decoding support for ICO (patchset #8 id:140001 of https://codereview.chromium.org/2044093002/ )
Reason for revert:
I think this broke a Dr Memory bot:

First breaking build:
https://build.chromium.org/p/chromium.memory.fyi/builders/Windows%20Unit%20%28DrMemory%29/builds/5084

ICOImageDecoderTests.parseAndDecodeByteByByte:
c:\b\build\slave\drm-cr\build\src\third_party\webkit\source\platform\image-decoders\imagedecodertesthelpers.cpp(83): error: Expected: (frameCount) <= (decoder->frameCount()), actual: 2 vs 0
c:\b\build\slave\drm-cr\build\src\third_party\webkit\source\platform\image-decoders\imagedecodertesthelpers.cpp(83): error: Expected: (frameCount) <= (decoder->frameCount()), actual: 3 vs 0
c:\b\build\slave\drm-cr\build\src\third_party\webkit\source\platform\image-decoders\imagedecodertesthelpers.cpp(83): error: Expected: (frameCount) <= (decoder->frameCount()), actual: 1 vs 0
c:\b\build\slave\drm-cr\build\src\third_party\webkit\source\platform\image-decoders\imagedecodertesthelpers.cpp(83): error: Expected: (frameCount) <= (decoder->frameCount()), actual: 1 vs 0

Original issue's description:
> Blink image-decoders: (lazy) deferred image decoding support for ICO
>
> BUG=513306
>
> Committed: https://crrev.com/de72effc185c6093879a0bc3379e38cb19b5b02b
> Cr-Commit-Position: refs/heads/master@{#399855}

TBR=scroggo@chromium.org,noel@chromium.org,fmalita@chromium.org,pkasting@chromium.org,aleksandar.stojiljkovic@intel.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=513306

Review-Url: https://codereview.chromium.org/2070723002
Cr-Original-Commit-Position: refs/heads/master@{#400030}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 20684d8c982d782714864ee967625eb10d2ebc76