Revert of Add plumbing in blink to allow overriding the default font collection. (patchset #15 id:300001 of https://codereview.chromium.org/1591883002/ )
Reason for revert:
This patch is breaking GPU builds --

See https://build.chromium.org/p/chromium.gpu/builders/GPU%20Win%20Builder/builds/37280
specifically.

We're seeing the error:
e:\b\build\slave\gpu_win_builder\build\src\third_party\webkit\source\platform\fonts\win\fontcacheskiawin.cpp(101) : error C3861: 'adopted': identifier not found

Original issue's description:
> Add plumbing in blink to allow overriding the skia font manager. This allows Chromium to use a custom font collection with skia, without having to patch the vtable of the DirectWrite factory.
>
> Note that this change depends on skia change https://codereview.chromium.org/1607083003/ which must land first.
>
> BUG=
>
> Committed: https://crrev.com/0e752e79260c775500c78cc351887fc19410bd8b
> Cr-Commit-Position: refs/heads/master@{#374482}

TBR=bungeman@chromium.org,dglazkov+blink@chromium.org,tfarina@chromium.org,bungeman@google.com,scottmg@chromium.org,pfeldman@chromium.org,kulshin@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=

Review URL: https://codereview.chromium.org/1682813004

Cr-Original-Commit-Position: refs/heads/master@{#374497}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 94fb5d4a5bf05e7d230c29be6df8ea1a21628032